# permissions for end users to edit devices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: device-editor-role
rules:
- apiGroups:
  - star.vpn-planet
  resources:
  - devices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - star.vpn-planet
  resources:
  - devices/status
  verbs:
  - get
