# permissions for end users to view devices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: device-viewer-role
rules:
- apiGroups:
  - star.vpn-planet
  resources:
  - devices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - star.vpn-planet
  resources:
  - devices/status
  verbs:
  - get
